### ISSUE TITLE
Miss something

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IndiansIncredible/mysqlbulkcopy#3]
```
Source Code miss something。

```

Original issue reported on code.google.com by `kongling...@gmail.com` on 24 Aug 2013 at 8:57

Attachments:
* [error.jpg](https://storage.googleapis.com/google-code-attachments/mysqlbulkcopy/issue-3/comment-0/error.jpg)

**Comment by IndiansIncredible** [comment]
The MySql.Data is the connector used by the class library. You can download the 6.5 version of connector from dev.mysql.com

The BatchSizeCompletedEventArgs missing issue is fixed.
